FROM nginx:alpine

RUN echo '<!DOCTYPE html><html><head><title>Azure DevSecOps Lab</title></head><body><h1>Azure DevSecOps Lab</h1><h2>Running on AKS</h2><h3>Created by Karthik</h3><p>My First Successful Azure DevSecOps Project ??</p></body></html>' > /usr/share/nginx/html/index.html

EXPOSE 80
